/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.44.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export { ScriptAbi__factory } from './factories/ScriptAbi__factory';